### ISSUE TITLE
appiumServerMngUrl如何使用？

### ISSUE THREAD

**Issue by lqhSniper** [jingpeicomp/autotest-framework#1]
配置的Servers，是否需要提前部署？   
使用过程中，尝试`autotest.appiumServerMngEnable=true` 但服务器无法启动。
执行至此失败：`Map response = restTemplate.postForObject(url, requestBody, Map.class);`

**Comment by jingpeicomp** [comment]
需要部署Appium Server管理程序，项目地址：https://github.com/jingpeicomp/appium-server 
autotest.appiumServerMngUrl 变量的值就是appium server对外提供web服务的url
